feat: add annotations form adaption support
halo-sigs/plugin-photos pull request #19
Opened 2023-08-02 13:59 UTC by LIlGG

#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #14

#### What this PR does / why we need it:

添加模型元数据表单定义的支持。

![image](https://github.com/halo-sigs/plugin-photos/assets/31335418/4b57adc0-21ec-49af-a849-442003a4849b)

![image](https://github.com/halo-sigs/plugin-photos/assets/31335418/efb5568a-39bf-4f34-9ce2-6e282fe89845)

#### Does this PR introduce a user-facing change?
```release-note
添加模型元数据表单定义的支持。
```

2023-08-02 13:59 UTC, LIlGG commented
/hold 等待 plugin-2.9.0-snapshot 发布后适配 VO。

2023-08-02 14:23 UTC, ruibaby requested changes

2023-08-02 14:23 UTC, ruibaby commented on README.md
> +| 链接分组 | core.halo.run | PhotoGroup |
描述不对

2023-08-02 15:47 UTC, LIlGG commented
/unhold

2023-08-03 03:11 UTC, guqing reviewed
/lgtm

<img width="582" alt="image" src="https://github.com/halo-sigs/plugin-photos/assets/38999863/d72c18f1-1f94-497c-9b20-9688713bcdde">

功能符合预期👍

2023-08-03 04:34 UTC, JohnNiang approved these changes
/lgtm

2023-08-03 06:11 UTC, ruibaby approved these changes

2023-08-03 06:48 UTC, merged